@startuml
' https://plantuml.com/class-diagram

' Core domain
abstract class AbstractFlyingObject {
    # locationX:int
    # locationY:int
    # speedX:int
    # speedY:int
    # image:BufferedImage
    # width:int
    # height:int
    # isValid:boolean

    + AbstractFlyingObject(int locationX, int locationY, int speedX, int speedY)
    + forward():void
    + crash(AbstractFlyingObject):boolean
    + setLocation(double,double):void
    + getLocationX():int
    + getLocationY():int
    + getSpeedY():int
    + getImage():BufferedImage
    + getWidth():int
    + getHeight():int
    + notValid():boolean
    + vanish():void
}

abstract class AbstractAircraft {
    # maxHp:int
    # hp:int
    # shootNum:int
    # power:int
    # direction:int

    + AbstractAircraft(int locationX,int locationY,int speedX,int speedY,int hp)
    + decreaseHp(int):void
    + getHp():int
    + {abstract} shoot():List<BaseBullet>
}

class EnemyAircraft {
    + EnemyAircraft(int locationX,int locationY,int speedX,int speedY,int hp)
    + createProp():BaseProp
    + forward_x():void
    + {abstract} addScore():int
}

AbstractFlyingObject <|-- AbstractAircraft
AbstractAircraft <|-- EnemyAircraft

' Hero
class HeroAircraft {
    - shootNum:int
    - power:int
    - direction:int
    - trajectoryFlag:int
    - shootStrategy1:ShootStrategy
    - shootStrategy2:ShootStrategy
    - shootStrategy3:ShootStrategy

    + getHeroAircraft():HeroAircraft
    + forward():void
    + shoot():List<BaseBullet>
    + changeTrajectory(BaseProp):void
    + recoverTrajectory():void
    + addHp(int):void
}
AbstractAircraft <|-- HeroAircraft
HeroAircraft o--> ShootStrategy

' Enemy types
class MobEnemy {
    + MobEnemy(int,int,int,int,int)
    + forward():void
    + shoot():List<BaseBullet>
}
class EliteEnemy {
    + EliteEnemy(int,int,int,int,int)
    + forward():void
    + shoot():List<BaseBullet>
}
class ElitePlusEnemy {
    + ElitePlusEnemy(int,int,int,int,int)
    + forward():void
    + shoot():List<BaseBullet>
}
class EliteProEnemy {
    + EliteProEnemy(int,int,int,int,int)
    + forward():void
    + shoot():List<BaseBullet>
}
class BossEnemy {
    + BossEnemy(int,int,int,int,int)
    + forward():void
    + shoot():List<BaseBullet>
}

EnemyAircraft <|-- MobEnemy
EnemyAircraft <|-- EliteEnemy
EnemyAircraft <|-- ElitePlusEnemy
EnemyAircraft <|-- EliteProEnemy
EnemyAircraft <|-- BossEnemy

' Bullets
abstract class BaseBullet {
    - power:int
    + BaseBullet(int,int,int,int,int)
    + forward():void
    + getPower():int
}
class HeroBullet
class EnemyBullet
BaseBullet <|-- HeroBullet
BaseBullet <|-- EnemyBullet
AbstractFlyingObject <|-- BaseBullet

' Props
abstract class BaseProp {
    + BaseProp(int,int,int,int)
    + forward():void
    + apply(HeroAircraft,BaseProp):void
}
class BloodProp
class BombProp
class BulletProp
class BulletPlusProp
class FreezeProp

BaseProp <|-- BloodProp
BaseProp <|-- BombProp
BaseProp <|-- BulletProp
BaseProp <|-- BulletPlusProp
BaseProp <|-- FreezeProp
AbstractFlyingObject <|-- BaseProp

' Shooting strategy (Strategy pattern)
interface ShootStrategy {
    + shoot(AbstractAircraft,int,int,int):List<BaseBullet>
}
class StraightShoot
class ScatterShoot
class CircleShoot
ShootStrategy <|.. StraightShoot
ShootStrategy <|.. ScatterShoot
ShootStrategy <|.. CircleShoot

' Enemy factory (Factory pattern)
interface EnemyManager {
    + createEnemy():EnemyAircraft
}
class ModEnemyFactory
class EliteEnemyFactory
class ElitePlusEnemyFactory
class EliteProEnemyFactory
class BossEnemyFactory

EnemyManager <|.. ModEnemyFactory
EnemyManager <|.. EliteEnemyFactory
EnemyManager <|.. ElitePlusEnemyFactory
EnemyManager <|.. EliteProEnemyFactory
EnemyManager <|.. BossEnemyFactory

' Application layer
class PropManager {
    + createProp(String,int,int,int,int):BaseProp
}
class ImageManager {
    + get(Object):BufferedImage
    + get(String):BufferedImage
}
class Game {
    - heroAircraft:HeroAircraft
    - enemyAircrafts:List<EnemyAircraft>
    - heroBullets:List<BaseBullet>
    - enemyBullets:List<BaseBullet>
    - props:List<BaseProp>
    - mobFactory:EnemyManager
    - eliteFactory:EnemyManager
    - elitePlusFactory:EnemyManager
    - eliteProFactory:EnemyManager
    - bossFactory:EnemyManager
    + action():void
}
class HeroController

Game --> HeroAircraft
Game --> EnemyAircraft
Game --> BaseBullet
Game --> BaseProp
Game --> EnemyManager
Game --> PropManager
Game --> HeroController
Game --> ImageManager
HeroController --> HeroAircraft
PropManager ..> BaseProp
ImageManager ..> HeroAircraft

@enduml
